!/bin/bash
#$ -N plANNTs fit1
#$ -l mem=16G
#$ -l cuda=1
#$ -l cuda_cores=3584
#$ -pe default 2


export PATH="/net/store/ai/projects/bert/miniconda/bin/bin:$PATH"
export CHECKPOINT_PATH="/net/store/ai/projects/bert/output/jo"

source activate tensorflow

python "/net/store/ai/projects/bert/repo/bert/run_classifier_jo_ddc_low_verbose_no_maxstep_continous.py" \
--task_name=categories \
--do_train=true \
--do_lower_case=false \
--do_eval=true \
--data_dir="/net/store/ai/projects/bert/data/student_data/data_jo/" \
--vocab_file=$BERT_BASE_DIR/vocab.txt \
--bert_config_file=$BERT_BASE_DIR/bert_config.json \
--init_checkpoint=$CHECKPOINT_PATH/new_output/model.ckpt-$MODEL_INDEX \
--max_seq_length=32 \
--train_batch_size=4 \
--learning_rate=2e-5 \
--num_train_epochs=1 \
--output_dir="/net/store/ai/projects/bert/output/jo/new_output/"

conda deactivate
